#!/usr/bin/env python3
"""Build the single-file Colab notebooks from the Jupytext sources.

The Colab bundles used to be hand-edited copies that drifted from
`notebooks/`. Now they are generated: `lab22/*.py` is written with
`%%writefile`, then every notebook's cells follow in order.

    python scripts/build_colab.py          # rewrite colab/*.ipynb
    python scripts/build_colab.py --check  # exit 1 if they are stale
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
WORKDIR = "/content/lab22"
STAGES = [
    ("00_dpo_loss_from_scratch", "core · CPU"),
    ("01_sft_mini", "core"),
    ("02_preference_data", "core"),
    ("03_dpo_train", "core"),
    ("03b_dpo_variants", "bonus"),
    ("04_compare_and_eval", "core"),
    ("05_merge_deploy_gguf", "bonus"),
    ("06_benchmark", "bonus"),
    ("07_grpo_bonus", "bonus"),
]
TARGETS = {"T4": "Lab22_DPO_T4.ipynb", "BIGGPU": "Lab22_DPO_BigGPU.ipynb"}
CELL = re.compile(r"^# %%(?P<md> \[markdown\])?.*$", re.MULTILINE)


def requirements() -> list[str]:
    """Requirement specs from requirements.txt, minus test/notebook tooling."""
    skip = ("jupyterlab", "jupytext", "pytest")
    specs = []
    for line in (REPO / "requirements.txt").read_text(encoding="utf-8").splitlines():
        spec = line.split("#", 1)[0].strip()
        if spec and not spec.startswith(skip):
            specs.append(spec)
    return specs


def source_lines(text: str) -> list[str]:
    lines = text.splitlines(keepends=True)
    if lines:
        lines[-1] = lines[-1].rstrip("\n")
    return lines


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source_lines(text)}


def code(text: str) -> dict:
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source_lines(text)}


def percent_cells(path: Path) -> list[dict]:
    """Parse a Jupytext py:percent file (header block dropped)."""
    text = path.read_text(encoding="utf-8")
    marks = list(CELL.finditer(text))
    cells = []
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(text)
        body = text[m.end() :end].strip("\n")
        if not body.strip():
            continue
        if m.group("md"):
            body = "\n".join(line[2:] if line.startswith("# ") else line.lstrip("#") for line in body.splitlines())
            cells.append(md(body))
        else:
            cells.append(code(body))
    return cells


RELEASE_GPU = (
    "# Free GPU memory held by the previous stage (model, trainer, llama.cpp handle).\n"
    "import gc\n"
    "for _name in ('trainer', 'model', 'ref_model', 'llm', 'policy', 'ref', 'tokenizer'):\n"
    "    globals().pop(_name, None)\n"
    "gc.collect()\n"
    "try:\n"
    "    import torch\n"
    "    if torch.cuda.is_available():\n"
    "        torch.cuda.empty_cache()\n"
    "        print(f'GPU memory in use: {torch.cuda.memory_allocated() / 1e9:.2f} GB')\n"
    "except ImportError:\n"
    "    pass"
)


def render(tier: str) -> dict:
    big = tier == "BIGGPU"
    pins = " ".join(f'"{s}"' for s in requirements())
    cells = [
        md(
            f"# Lab 22 — DPO/ORPO Alignment ({'BigGPU' if big else 'T4'} tier)\n\n"
            "**Track 3 · Day 22 · VinUni AICB.** Generated by `scripts/build_colab.py` from "
            "`notebooks/*.py` and `lab22/*.py`; do not edit by hand.\n\n"
            "Core: NB0 → NB4. Bonus: NB3b (variants), NB5 (GGUF), NB6 (lm-eval), NB7 (GRPO).\n"
            "Each stage reloads what it needs from disk, so after a crash you can restart the "
            "runtime, rerun section A, and continue from the stage that failed."
        ),
        md("## A. Setup"),
        code(
            "import os\n"
            f'os.environ["COMPUTE_TIER"] = "{tier}"\n'
            "# NB4 judges automatically with a panel of two local reward models (no key needed).\n"
            "# Optional API judge as a cross-check (two A/B orders):\n"
            '# os.environ["JUDGE_PROVIDER"] = "gemini"   # or "openai" / "anthropic"\n'
            '# os.environ["JUDGE_MODEL"] = "<current model id>"\n'
            '# from google.colab import userdata; os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")\n'
            "# Put API keys in Colab secrets, never in the notebook."
        ),
        code(f"!pip install -q {pins}" + (' "vllm>=0.10"' if big else "")),
        code(
            "from pathlib import Path\n"
            f'WORK = Path("{WORKDIR}")\n'
            '(WORK / "lab22").mkdir(parents=True, exist_ok=True)\n'
            "os.chdir(WORK)\n"
            "print(Path.cwd())"
        ),
        md("### Helper package `lab22/` (same files as the repo)"),
    ]
    for module in sorted((REPO / "lab22").glob("*.py")):
        body = module.read_text(encoding="utf-8")
        cells.append(code(f"%%writefile {WORKDIR}/lab22/{module.name}\n{body}"))
    for i, (stem, kind) in enumerate(STAGES):
        if i:
            # One Colab kernel runs every stage, so drop the previous stage's GPU objects.
            cells.append(code(RELEASE_GPU))
        cells.append(md(f"---\n# ⏵ `notebooks/{stem}.py` ({kind})"))
        cells.extend(percent_cells(REPO / "notebooks" / f"{stem}.py"))
    return {
        "cells": cells,
        "metadata": {
            "accelerator": "GPU",
            "colab": {"gpuType": "A100" if big else "T4", "provenance": []},
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if colab/*.ipynb differ from the sources")
    args = parser.parse_args()
    stale = []
    for tier, name in TARGETS.items():
        path = REPO / "colab" / name
        nb = render(tier)
        if args.check:
            if not path.exists() or json.loads(path.read_text(encoding="utf-8")) != nb:
                stale.append(name)
            continue
        path.write_text(json.dumps(nb, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"wrote colab/{name} ({len(nb['cells'])} cells)")
    if stale:
        print(f"stale: {stale}; run `python scripts/build_colab.py`")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
